# fly.toml app configuration file generated for animegarden-web-production on 2025-04-09T22:04:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animegarden-web-production'
primary_region = 'lax'

[build]
dockerfile = 'Dockerfile'

[build.args]
NODE_VERSION = '24.3.0'
PNPM_VERSION = '10.13.1'
APP_HOST = 'animes.garden'
FEED_HOST = 'api.animes.garden'
SERVER_URL = 'http://animegarden-server-production.flycast/'
FEED_SERVER_URL = 'http://animegarden-feed-production.flycast/'
UMAMI_ID = 'bcff225d-6590-498e-9b39-3a5fc5c2b4d1'

[processes]
server = 'node apps/web/server.mjs'

[http_service]
internal_port = 3000
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1
processes = ['server']

[[http_service.checks]]
grace_period = "30s"
interval = "60s"
timeout = "10s"
method = "GET"
path = "/health"

[[restart]]
policy = 'on-failure'
retries = 10
processes = ['server']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
