packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - bufferutil
  - core-js-pure
  - esbuild
  - fs-native-extensions
  - node-datachannel
  - sharp
  - tree-sitter
  - tree-sitter-json
  - tree-sitter-yaml
  - utf-8-validate
  - utp-native
  - workerd
