/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IframeRouteImport } from './routes/iframe'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as AnimeRouteRouteImport } from './routes/anime/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesPageRouteImport } from './routes/resources/$page'
import { Route as SubjectSubjectRouteRouteImport } from './routes/subject/$subject/route'
import { Route as DocsApiRouteRouteImport } from './routes/docs/api/route'
import { Route as CollectionHashRouteRouteImport } from './routes/collection/$hash/route'
import { Route as SubjectSubjectPageRouteImport } from './routes/subject/$subject/$page'
import { Route as DetailProviderProviderIdRouteRouteImport } from './routes/detail/$provider/$providerId/route'

const IframeRoute = IframeRouteImport.update({
  id: '/iframe',
  path: '/iframe',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRouteRoute = AnimeRouteRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const ResourcesPageRoute = ResourcesPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const SubjectSubjectRouteRoute = SubjectSubjectRouteRouteImport.update({
  id: '/subject/$subject',
  path: '/subject/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRouteRoute = DocsApiRouteRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionHashRouteRoute = CollectionHashRouteRouteImport.update({
  id: '/collection/$hash',
  path: '/collection/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectPageRoute = SubjectSubjectPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => SubjectSubjectRouteRoute,
} as any)
const DetailProviderProviderIdRouteRoute =
  DetailProviderProviderIdRouteRouteImport.update({
    id: '/detail/$provider/$providerId',
    path: '/detail/$provider/$providerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteRoute
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/iframe': typeof IframeRoute
  '/collection/$hash': typeof CollectionHashRouteRoute
  '/docs/api': typeof DocsApiRouteRoute
  '/subject/$subject': typeof SubjectSubjectRouteRouteWithChildren
  '/resources/$page': typeof ResourcesPageRoute
  '/resources/': typeof ResourcesIndexRoute
  '/detail/$provider/$providerId': typeof DetailProviderProviderIdRouteRoute
  '/subject/$subject/$page': typeof SubjectSubjectPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/iframe': typeof IframeRoute
  '/collection/$hash': typeof CollectionHashRouteRoute
  '/docs/api': typeof DocsApiRouteRoute
  '/subject/$subject': typeof SubjectSubjectRouteRouteWithChildren
  '/resources/$page': typeof ResourcesPageRoute
  '/resources': typeof ResourcesIndexRoute
  '/detail/$provider/$providerId': typeof DetailProviderProviderIdRouteRoute
  '/subject/$subject/$page': typeof SubjectSubjectPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteRoute
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/iframe': typeof IframeRoute
  '/collection/$hash': typeof CollectionHashRouteRoute
  '/docs/api': typeof DocsApiRouteRoute
  '/subject/$subject': typeof SubjectSubjectRouteRouteWithChildren
  '/resources/$page': typeof ResourcesPageRoute
  '/resources/': typeof ResourcesIndexRoute
  '/detail/$provider/$providerId': typeof DetailProviderProviderIdRouteRoute
  '/subject/$subject/$page': typeof SubjectSubjectPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/resources'
    | '/$'
    | '/about'
    | '/iframe'
    | '/collection/$hash'
    | '/docs/api'
    | '/subject/$subject'
    | '/resources/$page'
    | '/resources/'
    | '/detail/$provider/$providerId'
    | '/subject/$subject/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/$'
    | '/about'
    | '/iframe'
    | '/collection/$hash'
    | '/docs/api'
    | '/subject/$subject'
    | '/resources/$page'
    | '/resources'
    | '/detail/$provider/$providerId'
    | '/subject/$subject/$page'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/resources'
    | '/$'
    | '/about'
    | '/iframe'
    | '/collection/$hash'
    | '/docs/api'
    | '/subject/$subject'
    | '/resources/$page'
    | '/resources/'
    | '/detail/$provider/$providerId'
    | '/subject/$subject/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRouteRoute: typeof AnimeRouteRoute
  ResourcesRouteRoute: typeof ResourcesRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  IframeRoute: typeof IframeRoute
  CollectionHashRouteRoute: typeof CollectionHashRouteRoute
  DocsApiRouteRoute: typeof DocsApiRouteRoute
  SubjectSubjectRouteRoute: typeof SubjectSubjectRouteRouteWithChildren
  DetailProviderProviderIdRouteRoute: typeof DetailProviderProviderIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iframe': {
      id: '/iframe'
      path: '/iframe'
      fullPath: '/iframe'
      preLoaderRoute: typeof IframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/resources/$page': {
      id: '/resources/$page'
      path: '/$page'
      fullPath: '/resources/$page'
      preLoaderRoute: typeof ResourcesPageRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/subject/$subject': {
      id: '/subject/$subject'
      path: '/subject/$subject'
      fullPath: '/subject/$subject'
      preLoaderRoute: typeof SubjectSubjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$hash': {
      id: '/collection/$hash'
      path: '/collection/$hash'
      fullPath: '/collection/$hash'
      preLoaderRoute: typeof CollectionHashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subject/$page': {
      id: '/subject/$subject/$page'
      path: '/$page'
      fullPath: '/subject/$subject/$page'
      preLoaderRoute: typeof SubjectSubjectPageRouteImport
      parentRoute: typeof SubjectSubjectRouteRoute
    }
    '/detail/$provider/$providerId': {
      id: '/detail/$provider/$providerId'
      path: '/detail/$provider/$providerId'
      fullPath: '/detail/$provider/$providerId'
      preLoaderRoute: typeof DetailProviderProviderIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteRouteChildren {
  ResourcesPageRoute: typeof ResourcesPageRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteRouteChildren: ResourcesRouteRouteChildren = {
  ResourcesPageRoute: ResourcesPageRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteRouteWithChildren = ResourcesRouteRoute._addFileChildren(
  ResourcesRouteRouteChildren,
)

interface SubjectSubjectRouteRouteChildren {
  SubjectSubjectPageRoute: typeof SubjectSubjectPageRoute
}

const SubjectSubjectRouteRouteChildren: SubjectSubjectRouteRouteChildren = {
  SubjectSubjectPageRoute: SubjectSubjectPageRoute,
}

const SubjectSubjectRouteRouteWithChildren =
  SubjectSubjectRouteRoute._addFileChildren(SubjectSubjectRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRouteRoute: AnimeRouteRoute,
  ResourcesRouteRoute: ResourcesRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  IframeRoute: IframeRoute,
  CollectionHashRouteRoute: CollectionHashRouteRoute,
  DocsApiRouteRoute: DocsApiRouteRoute,
  SubjectSubjectRouteRoute: SubjectSubjectRouteRouteWithChildren,
  DetailProviderProviderIdRouteRoute: DetailProviderProviderIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
