name: 🐞 Bug report

description: Report an issue

labels:
  - bug

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: The link for the URL of bug page or [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)
      placeholder: https://garden.onekuma.cn

  - type: textarea
    id: browser-info
    attributes:
      label: Browser Info
      description: Output of `npx envinfo --browsers`
      render: Shell
      placeholder: Browsers
