### List the first page of resources
GET https://garden.onekuma.cn/api/resources
Content-Type: application/json

### List the second page of resources
GET https://garden.onekuma.cn/api/resources?page=2
Content-Type: application/json

### List resources from the 21st to 40th
GET https://garden.onekuma.cn/api/resources?page=2&count=20
Content-Type: application/json

### List resources with more filter
GET https://garden.onekuma.cn/api/resources?type=動畫&after=2023-04-15T16:00:00.000Z&before=1681578000000
Content-Type: application/json

### Search resources
GET https://garden.onekuma.cn/api/resources/search
Content-Type: application/json

{
  "include": ["機動戰士鋼彈 水星的魔女"]
}

### Only search 動畫
GET https://garden.onekuma.cn/api/resources/search?type=動畫
Content-Type: application/json

{
  "include": ["间谍过家家"]
}

### Search resources with exclude
GET https://garden.onekuma.cn/api/resources/search
Content-Type: application/json

{
  "include": ["复仇者"],
  "exclude": ["东京复仇者"]
}

### Search resources with complicated search
### Resource must has type "動畫"
### Resource title must contains ("機動戰士鋼彈" or "机动战士高达") and "水星的魔女" and ("第二季" or "Season 2" or "S2")
GET https://garden.onekuma.cn/api/resources/search?type=動畫
Content-Type: application/json

{
  "include": [
    ["機動戰士鋼彈", "机动战士高达"],
    "水星的魔女",
    ["第二季", "Season 2", "S2"]
  ]
}

### List all the users
GET https://garden.onekuma.cn/api/users
Content-Type: application/json

### List all the teams
GET https://garden.onekuma.cn/api/teams
Content-Type: application/json
