### List the first page of resources
GET https://garden.breadio.wiki/api/resources
Content-Type: application/json

### Get the resource detail
GET https://garden.breadio.wiki/api/resource/638270_Nemuri_THE_iDOLM_STER_CINDERELLA_GIRLS_2012-2023_Discography_Collection_268_CDs_FLAC.html
Content-Type: application/json

### Get the resource detail by id
GET https://garden.breadio.wiki/api/resource/652885
Content-Type: application/json

### List the second page of resources
GET https://garden.breadio.wiki/api/resources?page=2
Content-Type: application/json

### List resources from the 21st to 40th
GET https://garden.breadio.wiki/api/resources?page=2&pageSize=20
Content-Type: application/json

### List resources with more filter
GET https://garden.breadio.wiki/api/resources?type=動畫&fansubId=803&publisherId=727168&after=2023-04-16T13:00:00.000Z&before=1681653600000
Content-Type: application/json

### List resources from specific fansubs
GET https://garden.breadio.wiki/api/resources?fansubId=[833,619]&fansubName="爱恋字幕社"
Content-Type: application/json

### Search resources
GET https://garden.breadio.wiki/api/resources
Content-Type: application/json

{
  "include": ["機動戰士鋼彈 水星的魔女"]
}

### Only search 動畫
GET https://garden.breadio.wiki/api/resources?type=動畫
Content-Type: application/json

{
  "include": ["间谍过家家"]
}

### Search resources with exclude
GET https://garden.breadio.wiki/api/resources
Content-Type: application/json

{
  "include": ["复仇者"],
  "exclude": ["东京复仇者"]
}

### Search resources with complicated search
### Resource must has type "動畫"
### Resource title must contains one of ("机动战士高达" or "水星的魔女") and all the keywords ("第二季" and "ANi")
GET https://garden.breadio.wiki/api/resources?type=動畫
Cache-Control: no-store
Content-Type: application/json

{
  "include": [
    "机动战士高达",
    "水星的魔女",
  ],
  "keywords": [
    "第二季",
    "ANi"
  ]
}

### Search resources with full text index
GET https://garden.breadio.wiki/api/resources?type=動畫
Cache-Control: no-cache
Content-Type: application/json

{
  "search": [
    "我推的孩子",
    "简体"
  ]
}

### List all the users
GET https://garden.breadio.wiki/api/users
Content-Type: application/json

### List all the teams
GET https://garden.breadio.wiki/api/teams
Content-Type: application/json
