### Fetch all users
GET http://0.0.0.0:8080/users
Content-Type: application/json

### Fetch all teams
GET http://0.0.0.0:8080/users
Content-Type: application/json

### Fetch all subjects
GET http://0.0.0.0:8080/subjects
Content-Type: application/json

### Trigger fetch dmhy resources
POST http://0.0.0.0:8080/admin/resources/dmhy
Authorization: Bearer 123456
Content-Type: application/json

### Trigger fetch moe resources
POST http://0.0.0.0:8080/admin/resources/moe
Authorization: Bearer 123456
Content-Type: application/json

### Trigger fetch ani resources
POST http://0.0.0.0:8080/admin/resources/ani
Authorization: Bearer 123456
Content-Type: application/json

###
POST http://0.0.0.0:8080/resources
Content-Type: application/json

{
  "search": ["愚蠢天使与恶魔共舞"]
}

###
POST http://0.0.0.0:8080/resources
Cache-Control: no-store
Content-Type: application/json

{
  "include": ["金属胭脂"],
  "keywords": ["ANi"]
}

###
GET http://0.0.0.0:8080/dmhy/detail/660700
Content-Type: application/json
