### Fetch all users
GET http://0.0.0.0:8080/users
Content-Type: application/json

### Fetch all teams
GET http://0.0.0.0:8080/users
Content-Type: application/json

### Fetch all subjects
GET http://0.0.0.0:8080/subjects
Content-Type: application/json

### Trigger fetch dmhy resources
POST http://0.0.0.0:8080/admin/resources/dmhy
Authorization: Bearer 123456
Content-Type: application/json

### Trigger fetch moe resources
POST http://0.0.0.0:8080/admin/resources/moe
Authorization: Bearer 123456
Content-Type: application/json

### Trigger fetch ani resources
POST http://0.0.0.0:8080/admin/resources/ani
Authorization: Bearer 123456
Content-Type: application/json

### Fetch 动画
POST http://0.0.0.0:8080/resources
Content-Type: application/json

{
  "page": 1,
  "pageSize": 80,
  "type": "动画"
}

### Fetch ANi
POST http://0.0.0.0:8080/resources
Content-Type: application/json

{
  "page": 1,
  "pageSize": 80,
  "fansub": "ANi"
}

### Search
POST http://0.0.0.0:8080/resources
Content-Type: application/json

{
  "search": [
    "[北宇治字幕组]",
    "赛马娘剧场版",
    "新时代之门",
    "/",
    "新时代之扉",
    "/",
    "Uma",
    "Musume",
    "Pretty",
    "Derby",
    "Beginning",
    "of",
    "a",
    "New",
    "Era"
  ]
}

### Subjects
POST http://0.0.0.0:8080/resources?subject=504591
Content-Type: application/json

### Title search
POST http://0.0.0.0:8080/resources
Cache-Control: no-store
Content-Type: application/json

{
  "include": ["金属胭脂"],
  "keywords": ["ANi"]
}

###
GET http://0.0.0.0:8080/dmhy/detail/660700
Content-Type: application/json

### Sitemap
GET http://0.0.0.0:8080/sitemaps/2025/01
Content-Type: application/json

### Feed
GET http://0.0.0.0:8080/feed.xml

### Collection
GET http://0.0.0.0:8080/collection/RUi8lloFMts8DjeI97lIGfFE5zz6MM9a-Qek7xaEY78
Content-Type: application/json
